### ISSUE TITLE
In desktop Safari drag preview can include elements behind container.

### ISSUE THREAD

**Issue by IanBellomy** [atlassian/pragmatic-drag-and-drop#43] opened 2024-04-26 02:13 UTC
In desktop Safari 17.4.1 a drag preview created by rendering an element into the provided container via react's createRoot can result in other elements in the top left being visually included in the preview image. 

https://github.com/atlassian/pragmatic-drag-and-drop/assets/17239616/8f1ec797-cae3-4211-a2c4-16731bde7c5b

**Repro:**
https://codesandbox.io/p/sandbox/safari-pdnd-preview-issue-react-2cl6k4?file=%2Fsrc%2FDragMe.jsx

Works fine in Chrome 124 and FF 125.

**Comment by alexreardon** [comment] 2024-04-28 23:28
We are aware of this browser bug. *shakes fist at safari

We have a fix for this bug in `setCustomNativeDragPreview()`. We generally recommend folks use that function when working with native drag previews as it provides the most resiliant experience. 

We didn't bake the `setCustomNativeDragPreview` into Pragmatic drag and drop (we made it an optional helper), because:

- sometimes the default native drag preview is good enough
- sometimes people want to hide the native drag preview and have no preview
- sometimes people want to hide the native drag preview and use a custom drag preview

We have tried to make decisions that result in the lowest amount of code for all consumers.

Thanks for taking the time to raise this issue

**Comment by IanBellomy** [comment] 2024-04-29 14:34
🤔 The repro uses `setCustomNativeDragPreview`...

**Comment by alexreardon** [comment] 2024-04-29 22:32
I can reproduce the issue. It looks like our Safari fix is not working for this case (I can see that the `left` property is not being set correctly). I suspect the fix will be fairly minor and i'll get on it asap 🚀

**Comment by alexreardon** [comment] 2024-04-29 23:31
Our Safari workaround is working for `react@16` ([a forked example](https://codesandbox.io/p/sandbox/safari-pdnd-preview-issue-react-react-16-rx93n8?file=%2Fsrc%2FDragMe.jsx%3A1%2C27)). This is because I think that the new `createRoot().render()` renders after a microtask. I'll need to adjust our fix to accomodate for that

**Comment by alexreardon** [comment] 2024-04-30 00:53
I have a fix. 

```diff
   if (isSafari()) {
-    const rect = container.getBoundingClientRect();
-    container.style.left = `-${rect.width - 0.0001}px`;
+    /**
+     *  For some frameworks (eg `react@18+` with `ReactDOM.createRoot().render()`) the rendering
+     *  inside the `container` does not occur until after a microtask.
+     **/
+    queueMicrotask(() => {
+      const rect = container.getBoundingClientRect();
+
+      // We cannot apply a fix if nothing has been rendered into the `container`
+      if (rect.width === 0) {
+        return;
+      }
+
+      container.style.left = `-${rect.width - 0.0001}px`;
+    });
   }
```

You can apply this fix on your end in the short term if you like

https://codesandbox.io/p/sandbox/safari-pdnd-preview-issue-react-with-fix-gsw2jw?file=%2Fsrc%2FDragMe.jsx%3A63%2C29

**Comment by alexreardon** [comment] 2024-04-30 02:51
@IanBellomy I have raised a pull request to our mono repo with a fix. I suspect this will be released within ~12 hours.

Thanks so much for raising this!

**Closed by alexreardon** 2024-04-30 02:51 UTC

**Comment by alexreardon** [comment] 2024-04-30 05:55
Fix merged. Should be released to `npm` soon
